// This file is auto-generated by Figma Make. Do not edit manually.
export const projectId = 'nqrjccjsnkbqzghyalzg';
export const publicAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xcmpjY2pzbmticXpnaHlhbHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyODI5MjMsImV4cCI6MjA1MTg1ODkyM30.TUgL1c4NjboBfz8k2aHiPEKaOcwPfvC8c7_K8rJbzIM';