// This file is auto-generated by Figma Make. Do not edit manually.
export const projectId = 'gzwnlrxilxdserfaxypn';
export const publicAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6d25scnhpbHhkc2VyZmF4eXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzI3MDcsImV4cCI6MjA3MjgwODcwN30.ULfmEUJ_rodRkSdpWsgUrb4MWPQ0rWmbOvBwKSRHVBY';
